[sensor]
id = "3c32afb6-ff49-448f-8a07-2693bdd3abc0"
name = "humidity sensor"
topic = "sensors_topic"
data_topic = "sensor_readings_topic"
frequency = 1.0
type = "Distance"

[producer]
bootstrap_servers = "broker:9092"
acks = 0
api_version = [3, 4, 0]